#!/usr/bin/perl -w
# $Id: //info.ravenbrook.com/project/mps/version/1.117/test/test/script/commands/clib#1 $
#
# Compile all the .c files in $testlib_dir,
# putting the resulting .o files in $obj_dir.
#

&requiredoptions(
 "MPS_INCLUDE_DIR",
 "MPS_LINK_OBJ",
 "VARIETY",
 "PLATFORM"
);

&clib;

