#!/usr/bin/perl -w
# $Id: //info.ravenbrook.com/project/mps/version/1.117/test/test/script/commands/runset#1 $
#
# run a set of tests specified in a test-set file
#

&requiredoptions(
 "MPS_INCLUDE_DIR",
 "MPS_LINK_OBJ",
 "VARIETY",
 "PLATFORM",
 "LOG_DIR"
);

@LOGS = ("$LOG_DIR/summ.log", "$LOG_DIR/res.log", "$LOG_DIR/full.log");
unlink(@LOGS);
foreach $testset (@ARGV) {
 &run_testset($testset, @LOGS);
}

